[project]
authors = ["Dha2511 <50593834+Dha2511@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ElbowExo"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
build = "maturin develop -m ./filter/Cargo.toml"

[dependencies]
python = ">=3.12.0,<4"
matplotlib = ">=3.9.2,<4"
scipy = ">=1.14.1,<2"
pyserial = ">=3.5,<4"
maturin = ">=1.7.4,<2"
pip = ">=24.2,<25"
librosa = ">=0.10.2.post1,<0.11"

[pypi-dependencies]
pywifi = ">=1.1.12"
pyqtgraph = ">=0.13.7"
pyqt5 = ">=5.15.11"
pillow = "*"
pynput = "*"
mss = "*"
